[package]
name = "pretty_debug"
description = "Simple crate for module based formatted console prints"
repository = "https://github.com/Kay-Conte/Debugger-rs"
version = "0.1.4"
edition = "2021"
license = "MIT"

[dependencies]
